name: cd

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  list-files:
    runs-on: self-hosted

    steps:
      - name: Pull Repo
        run: git pull
        
      - name: Stop containers
        run: docker compose -f docker-compose.prod.yml down

      - name: Start containers
        run: docker compose -f docker-compose.prod.yml up -d
