name: Test Runner Files

on:
  workflow_dispatch: # allows manual trigger from GitHub

jobs:
  list-files:
    runs-on: self-hosted  # make sure this runs on your server runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List current directory
        run: ls -la
    
      - name: See directory
      - run: pwd
