name: cd
        run: docker compose -f docker-compose.prod.yml down
        run: docker compose -f docker-compose.prod.yml up

on:
  workflow_dispatch: # allows manual trigger from GitHub

jobs:
  list-files:
    runs-on: self-hosted  # make sure this runs on your server runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop containers
        run: docker compose -f docker-compose.prod.yml down

      - name: Start containers
        run: docker compose -f docker-compose.prod.yml up -d
